name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        Example: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: |
        What other solutions or workarounds have you considered?
        Why are they not suitable?
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case or real-world scenario
      placeholder: |
        Provide a concrete example of how you would use this feature.
        This helps us understand the value and design better.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: (Optional) Do you have ideas for how this could be implemented?
      placeholder: |
        If you have technical suggestions or want to contribute,
        share your thoughts on the implementation approach.
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package should this feature be added to?
      options:
        - oauth2client
        - grpcclient
        - grpcserver
        - httpclient
        - httpserver
        - new package
        - multiple packages
        - other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: This feature aligns with the project's goals and scope
          required: false
        - label: I am willing to contribute to the implementation
          required: false